# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 15ad6270f41e222d4e1e42710c12024dff9f1cebe7d6853a1cbedbdd4182da9b04de8dc2ac506843a6405179aa3901c3cbefeeb692759a4b3b9a165bb58d9576

test:
  secret_key_base: b102574ee4b455b164d08810e5ed36797063a01d2900f211819f3139c14994746713aee69d1993a347d8135da021c2bdb34cb077686538c5b0dec42159f87215

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
